@backend_HostAddress = http://localhost:5038

############################################################## CRUD PESSOA

### Criar nova pessoa
POST {{backend_HostAddress}}/api/pessoas
Content-Type: application/json

{
  "nome": "João da Silva",
  "dataNascimento": "1990-05-15"
}


#### Listar todas as pessoas
GET {{backend_HostAddress}}/api/pessoas
Accept: application/json


### Editar uma pessoa
PUT {{backend_HostAddress}}/api/pessoas/id
Content-Type: application/json

{
  "nome": "João da Silva",
  "dataNascimento": "1990-05-15"
}


### Deletar uma pessoa
DELETE {{backend_HostAddress}}/api/pessoas/id


############################################################## CRUD TRANSAÇÃO

### Criar uma Transação
# 0 para despesa, 1 para receita
POST {{backend_HostAddress}}/api/transacoes
Content-Type: application/json

{
  "descricao": "Compra de supermercado",
  "valor": 150.75,
  "data": "2024-06-01",
  "tipo": 0,
  "pessoaId": "cbc4b824-1c6c-4f3e-aea2-d7d75352116b"
}

### Listar todas as transações
GET {{backend_HostAddress}}/api/transacoes
Accept: application/json

#### Editar uma transação
PUT {{backend_HostAddress}}/api/transacoes/id
Content-Type: application/json

{
  "descricao": "Compra de supermercado",
  "valor": 150.75,
  "data": "2024-06-01",
  "tipo": 0,
  "pessoaId": "id"
}

### Deletar uma transação
DELETE {{backend_HostAddress}}/api/transacoes/id
