// Dados de exemplo enquanto não há conexão com o banco de dados
export const pessoas = [
	{ nome: 'Virginia Simon', idade: 20, id: crypto.randomUUID() },
	{ nome: 'Jorge Phillips', idade: 2, id: crypto.randomUUID() },
	{ nome: 'Inez Tran', idade: 14, id: crypto.randomUUID() },
	{ nome: 'Alan Nguyen', idade: 55, id: crypto.randomUUID() },
	{ nome: 'Susie Tucker', idade: 72, id: crypto.randomUUID() },
	{ nome: 'Henrietta Reid', idade: 69, id: crypto.randomUUID() },

];

// mock-data gerado pelo chatGPT, com base em dados fictícios de pessoas e transações
export const transacoes = [
	{
		nome: 'Henrietta Reid',
		data: '2023-06-29T16:50:00',
		valor: 410.0,
		tipo: 'despesa',
		descricao: 'Pagamento de exames médicos e aquisição de medicamentos prescritos.',
		id: crypto.randomUUID(),
	},
	{
		nome: 'Susie Tucker',
		data: '2023-06-27T09:05:00',
		valor: 168.9,
		tipo: 'despesa',
		descricao: 'Pagamento de consulta médica de rotina e exames laboratoriais.',
		id: crypto.randomUUID(),
	},
	{
		nome: 'Inez Tran',
		data: '2023-06-22T14:00:00',
		valor: 210.5,
		tipo: 'despesa',
		descricao: 'Aquisição de uniforme e tênis para atividades escolares.',
		id: crypto.randomUUID(),
	},
	{
		nome: 'Virginia Simon',
		data: '2023-06-20T18:10:00',
		valor: 96.8,
		tipo: 'despesa',
		descricao: 'Compras de supermercado para abastecimento da casa.',
		id: crypto.randomUUID(),
	},
	{
		nome: 'Alan Nguyen',
		data: '2023-06-19T10:35:00',
		valor: 420.75,
		tipo: 'despesa',
		descricao: 'Manutenção preventiva e troca de óleo do automóvel.',
		id: crypto.randomUUID(),
	},
	{
		nome: 'Jorge Phillips',
		data: '2023-06-18T15:20:00',
		valor: 72.3,
		tipo: 'despesa',
		descricao: 'Aquisição de brinquedos educativos para desenvolvimento infantil.',
		id: crypto.randomUUID(),
	},
	{
		nome: 'Virginia Simon',
		data: '2023-06-15T12:00:00',
		valor: 320.45,
		tipo: 'despesa',
		descricao: 'Pagamento da conta de energia elétrica da residência.',
		id: crypto.randomUUID(),
	},
	{
		nome: 'Henrietta Reid',
		data: '2023-06-13T17:15:00',
		valor: 198.3,
		tipo: 'despesa',
		descricao: 'Compra de alimentos e produtos de limpeza no supermercado.',
		id: crypto.randomUUID(),
	},
	{
		nome: 'Susie Tucker',
		data: '2023-06-11T08:40:00',
		valor: 285.6,
		tipo: 'despesa',
		descricao: 'Compra de medicamentos de uso contínuo na farmácia.',
		id: crypto.randomUUID(),
	},
	{
		nome: 'Alan Nguyen',
		data: '2023-06-08T13:25:00',
		valor: 1450.0,
		tipo: 'despesa',
		descricao: 'Pagamento da parcela do financiamento do veículo.',
		id: crypto.randomUUID(),
	},
	{
		nome: 'Inez Tran',
		data: '2023-06-05T09:50:00',
		valor: 135.0,
		tipo: 'despesa',
		descricao: 'Compra de materiais escolares para o início do semestre.',
		id: crypto.randomUUID(),
	},
	{
		nome: 'Virginia Simon',
		data: '2023-06-04T16:30:00',
		valor: 185.9,
		tipo: 'despesa',
		descricao: 'Compra de materiais de escritório para uso no trabalho.',
		id: crypto.randomUUID(),
	},
	{
		nome: 'Jorge Phillips',
		data: '2023-06-03T11:10:00',
		valor: 48.9,
		tipo: 'despesa',
		descricao: 'Compra de fraldas, lenços umedecidos e produtos de higiene.',
		id: crypto.randomUUID(),
	},
	{
		nome: 'Henrietta Reid',
		data: '2023-06-02T14:45:00',
		valor: 3400.0,
		tipo: 'receita',
		descricao: 'Crédito referente ao pagamento mensal da aposentadoria.',
		id: crypto.randomUUID(),
	},
	{
		nome: 'Susie Tucker',
		data: '2023-06-02T10:20:00',
		valor: 3100.0,
		tipo: 'receita',
		descricao: 'Recebimento do benefício mensal de aposentadoria.',
		id: crypto.randomUUID(),
	},
	{
		nome: 'Alan Nguyen',
		data: '2023-06-01T09:15:00',
		valor: 6800.0,
		tipo: 'receita',
		descricao: 'Recebimento do salário mensal depositado pela empresa.',
		id: crypto.randomUUID(),
	},
	{
		nome: 'Virginia Simon',
		data: '2023-06-01T08:30:00',
		valor: 4200.0,
		tipo: 'receita',
		descricao: 'Recebimento do salário referente ao mês de junho.',
		id: crypto.randomUUID(),
	},
];